//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waTiendadeZapatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpleado()
        {
            this.tblPedido = new HashSet<tblPedido>();
            this.tblProducto = new HashSet<tblProducto>();
        }
    
        public int intCodigoEmpleado { get; set; }
        public string strNombreEmpleado { get; set; }
        public string strNombreEmpleado2 { get; set; }
        public string strApellidoEmpleado { get; set; }
        public string strApellidoEmpleado2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedido> tblPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducto> tblProducto { get; set; }
    }
}
