//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waTiendadeZapatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProducto()
        {
            this.tblPedido = new HashSet<tblPedido>();
        }
    
        public int intCodigoProducto { get; set; }
        public string strNombreProducto { get; set; }
        public string strTipoProducto { get; set; }
        public Nullable<int> intCodigoEmpleado { get; set; }
        public int Valor { get; set; }
    
        public virtual tblEmpleado tblEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedido> tblPedido { get; set; }
    }
}
